try
{
    setTimeout(function() {
    let numerator=10;
    let denominator=a;
    console.log(numerator/denominator);
    console.log(a)},3000);
}

catch(error)
{
    console.log("Error occured in this program");
    console.log("Error is "+error);
}